[workspace]
authors = ["Kainoa-h <kainoahowj@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "aoc_mojo"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.1.0.dev2025120205,<0.27"
